---
title: "graphics_tables"
author: "Leandro Pereira Garcia"
date: "October 10, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
set.seed(233)
```


```{r }
#Libraries
library(readr)
library(tidyverse)
library(ggplot2)
library(sf)
library(spData)
library(ggpubr)
library(RColorBrewer)
library(gt)
```


```{r include=FALSE}
#Databases
base_efi <- read_csv("bases/efficiency_analysis.csv")
pred <- read_csv("bases/impact_predictions.csv")
```




```{r }
#Importing the world map
WorldData <- map_data('world')
WorldData %>% filter(region != "Antarctica") -> WorldData
WorldData <- fortify(WorldData)

#Adjustin countries names
base_efi$region_map <- base_efi$LOCATION
base_efi[which(base_efi$LOCATION == "Congo, Rep."), 61] <- "Republic of Congo"
base_efi[which(base_efi$LOCATION == "Egypt, Arab Rep."), 61] <- "Egypt"
base_efi[which(base_efi$LOCATION == "Korea, Rep."), 61] <- "South Korea"
base_efi[which(base_efi$LOCATION == "North Macedonia"), 61] <- "Macedonia"
base_efi[which(base_efi$LOCATION == "Russian Federation"), 61] <- "Russia"
base_efi[which(base_efi$LOCATION == "Trinidad and Tobago"), 61] <- "Trinidad"
base_efi[which(base_efi$LOCATION == "United Kingdom"), 61] <- "UK"
base_efi[which(base_efi$LOCATION == "United States"), 61] <- "USA"

base_map <- base_efi
base_map <- merge(base_map, WorldData, by.x = "region_map", by.y = "region", all.x = T)

```


```{r }
#Neontal, 28d<U5, Tax, Public Expenditure distribution
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
mort_raw <- scale_fill_gradientn(colours = myPalette(10), limits=c(-4,1.5))

base_mapa_neo <- dplyr::select(base_map, c(region_map, DELTA_RATE_NEO))
plot1 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_neo, map=WorldData,
                  aes(fill= DELTA_RATE_NEO, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Var Neo 2016-2015", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        mort_raw

base_mapa_neo_u5 <- dplyr::select(base_map, c(region_map, DELTA_RATE_NEO_U5))
plot2 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_neo_u5, map=WorldData,
                  aes(fill= DELTA_RATE_NEO_U5, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Var 28d<u5 2016-2015", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        mort_raw

treat <- scale_fill_gradientn(colours = myPalette(10), limits=c(-4000,40000))


base_mapa_public <- dplyr::select(base_map, c(region_map, PUBLIC_EXP_LAGGED2))
plot3 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_public, map=WorldData,
                  aes(fill= PUBLIC_EXP_LAGGED2, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Pub Exp 2012-2011", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        treat

base_mapa_tax <- dplyr::select(base_map, c(region_map, TAX_PPP_LAGGED3))
plot4 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_tax, map=WorldData,
                  aes(fill= TAX_PPP_LAGGED3, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Tax 2010-2009", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        treat

ggarrange(plot1, plot2, plot3, plot4, labels = c("A", "B", "C", "D"),
           common.legend = F,legend = "bottom")



```



```{r impact_predictions}
# Create a gt table of impact per group of development
pred[which(pred$INCOME_CLASS == "L"), 2] <- "Low"
pred[which(pred$INCOME_CLASS == "LM"), 2] <- "Low-Median"
pred[which(pred$INCOME_CLASS == "UM"), 2] <- "Upper-Median"
pred[which(pred$INCOME_CLASS == "H"), 2] <- "High"
pred$INCOME_CLASS <- factor(pred$INCOME_CLASS, levels = c("Low", "Low-Median", "Upper-Median", "High"))
pred[,c(47:52)] <- pred[,c(47:52)]*1000
pred$IC_NEO <- paste0("(CI95%",round(pred$IC_05_NEO,3), " ", round(pred$IC_95_NEO,3),")")
pred$IC_NEO_U5 <- paste0("(CI95%",round(pred$IC_05_NEO_U5,3), " ", round(pred$IC_95_NEO_U5,3),")")


pred %>%
     dplyr::select("LOCATION", "INCOME_CLASS", "DELTA_RATE_NEO", 
                   "DELTA_RATE_NEO_U5", "PRED_NEO", "IC_NEO",
                   "PRED_NEO_U5", "IC_NEO_U5") %>%
      gt(groupname_col = "INCOME_CLASS") %>%
         tab_header(
            title = "Government Impact on Children Mortality"
         ) %>%
         fmt_number(
            columns = vars("DELTA_RATE_NEO", 
                   "DELTA_RATE_NEO_U5", "PRED_NEO", 
                   "PRED_NEO_U5"),
            decimals = 3
         ) %>%
         cols_merge(
            col_1 =  "PRED_NEO",
            col_2 = "IC_NEO"
         ) %>%
         cols_merge(
            col_1 =  "PRED_NEO_U5",
            col_2 = "IC_NEO_U5"
         ) %>% 
         cols_label(
            LOCATION = "Coutry",
            DELTA_RATE_NEO = "Var Neo",
            DELTA_RATE_NEO_U5 = "Var 28>U5", 
            PRED_NEO = "Impact Neo", 
            PRED_NEO_U5 = "Impact 28>U5"
         )

```


```{r }

lm(EFI ~ PROP_PUBLIC_HEALTH_EXP_LAGGED2, subset(base_efi,base_efi$INCOME_CLASS %in% c("L", "LM"))) %>%
   summary()

```





```{r }

final_base <- subset(base_efi,base_efi$INCOME_CLASS %in% c("L", "LM"))
ggplot(final_base,aes(PROP_PUBLIC_HEALTH_EXP_LAGGED2, EFI))+
   geom_jitter()+
   geom_smooth(method = "lm")+
   theme_bw()


```


```{r }
#neo,tag_neo, 28d<U5, targ_28d<U5 distribution
myPalette <- colorRampPalette(brewer.pal(11, "Spectral"))
mort <- scale_fill_gradientn(colours = myPalette(10), limits=c(0, 0.00004))

base_mapa_pred_neo <- dplyr::select(base_map, c(region_map, PRED_NEO))
plot1 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_pred_neo, map=WorldData,
                  aes(fill= PRED_NEO, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Impact", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        mort

base_mapa_targ_neo <- dplyr::select(base_map, c(region_map, TARG_PRED_NEO))
plot2 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_targ_neo, map=WorldData,
                  aes(fill= TARG_PRED_NEO, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Efficient impact neo", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        mort

base_mapa_pred_neo_u5 <- dplyr::select(base_map, c(region_map, PRED_NEO_U5))
plot3 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_pred_neo_u5, map=WorldData,
                  aes(fill= PRED_NEO_U5, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Current impact 28d<u5", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        mort

base_mapa_targ_neo_u5 <- dplyr::select(base_map, c(region_map, TARG_PRED_NEO_U5))
plot4 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_targ_neo_u5, map=WorldData,
                  aes(fill= TARG_PRED_NEO_U5, map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Efficient impact 28d<u5", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        mort


ggarrange(plot1, plot2, plot3, plot4, labels = c("A", "B", "C", "D"),
           common.legend = T,legend = "bottom")



```


```{r }
#health, targ_health, non_health, targ_non_health
myPalette <- colorRampPalette(brewer.pal(11, "Spectral"))
exp <- scale_fill_gradientn(colours = myPalette(10), limits=c(0, 11))


base_mapa_health <- dplyr::select(base_map, c(region_map, HEALTH))
plot1 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_health, map=WorldData,
                  aes(fill= log(HEALTH), map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Logged value", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        exp

base_mapa_targ_health <- dplyr::select(base_map, c(region_map, TARG_HEALTH))
plot2 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_targ_health, map=WorldData,
                  aes(fill= log(TARG_HEALTH), map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Efficient health exp", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        exp

base_mapa_non_health <- dplyr::select(base_map, c(region_map, NON_HEALTH))
plot3 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_non_health, map=WorldData,
                  aes(fill= log(NON_HEALTH), map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Current non health exp", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        exp

base_mapa_targ_non_health <- dplyr::select(base_map, c(region_map, TARG_NON_HEALTH))
plot4 <- ggplot()+
        geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)+
        geom_map(data=base_mapa_targ_non_health, map=WorldData,
                  aes(fill= log(TARG_NON_HEALTH), map_id=region_map),
                  colour="#7f7f7f", size=0.5)+
        coord_map("rectangular", lat0=0, xlim=c(-190,190), ylim=c(-60, 90))+
        labs(fill="Efficient non health exp", x="", y="")+
        theme_bw()+
        theme(panel.border = element_blank())+
        exp


ggarrange(plot1, plot2, plot3, plot4, labels = c("A", "B", "C", "D"),
           common.legend = T,legend = "bottom")




```







